version: 2

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      k8s.io:
        patterns:
          - "k8s.io/*"
        exclude-patterns:
          - "k8s.io/utils"
          - "k8s.io/klog/v2"
          - "k8s.io/kube-openapi"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
