
[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  name = "github.com/Masterminds/semver"
  version = "~1.3.1"

[[constraint]]
  name = "github.com/Masterminds/sprig"
  version = "2.14.1"

[[constraint]]
  name = "github.com/Masterminds/vcs"
  version = "~1.11.0"

[[constraint]]
  name = "github.com/asaskevich/govalidator"
  version = "4.0.0"

[[constraint]]
  name = "github.com/gobwas/glob"
  version = "0.2.1"

[[constraint]]
  name = "github.com/gosuri/uitable"
  branch = "master"

[[constraint]]
  name = "github.com/technosophos/moniker"
  branch = "master"

[[constraint]]
  name = "k8s.io/api"
  branch = "release-1.11"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.11"

[[constraint]]
  version = "kubernetes-1.11.2"
  name = "k8s.io/client-go"

[[constraint]]
  name = "k8s.io/kubernetes"
  branch = "release-1.11"

[[override]]
  name = "github.com/json-iterator/go"
  revision = "f2b4162afba35581b6d4a50d3b8f34e33c144682"

[[override]]
  name = "github.com/Azure/go-autorest"
  revision = "1ff28809256a84bb6966640ff3d0371af82ccba4"

[prune]
  go-tests = true
  unused-packages = true
